# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm ci --ignore-scripts

# Copy all source files
COPY . .

# Build the project
RUN npm run build

# Expose the port if needed (MCP typically uses stdio, so not necessary)

CMD ["node", "dist/index.js"]
